name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.75' # Adjust this to your Laravel version

      - name: Install Composer dependencies
        run: composer install

      - name: Copy .env file
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Run database migrations and seeders
        run: php artisan migrate --seed

      - name: Deploy to cPanel
        uses: wtfil/cpanel-deploy@v1
        with:
          cpanel_username: ${{ secrets.CPANEL_USERNAME }}
          cpanel_password: ${{ secrets.CPANEL_PASSWORD }}
          cpanel_host: ${{ secrets.CPANEL_HOST }}
          cpanel_port: ${{ secrets.CPANEL_PORT }}
          cpanel_directory: public_html/backend # Adjust to your folder structure
